apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    env:
      - name: NGINX_ROOT_USERNAME
        valueFrom:
          secretKeyRef:
             name: nginx-secret
             key: nginx-root-username
      - name: NGINX_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
             name: nginx-secret
             key: nginx-root-password
